from pathlib import Path

from sumo_optimise.conversion.demand.catalog import build_endpoint_catalog
from sumo_optimise.conversion.domain.models import PedestrianEndpoint, VehicleEndpoint
from sumo_optimise.conversion.parser.spec_loader import (
    build_clusters,
    load_json_file,
    load_schema_file,
    parse_defaults,
    parse_junction_templates,
    parse_layout_events,
    parse_main_road,
    parse_snap_rule,
    validate_json_schema,
)
from sumo_optimise.conversion.planner.lanes import (
    collect_breakpoints_and_reasons,
    compute_lane_overrides,
)


def _prepare_inputs():
    spec_path = Path("data/reference/SUMO_OPTX_v1.3_sample.json")
    schema_path = Path("src/sumo_optimise/conversion/data/schema.json")

    spec_json = load_json_file(spec_path)
    schema_json = load_schema_file(schema_path)
    validate_json_schema(spec_json, schema_json)

    snap_rule = parse_snap_rule(spec_json)
    defaults = parse_defaults(spec_json)
    main_road = parse_main_road(spec_json)
    junction_template_by_id = parse_junction_templates(spec_json)
    layout_events = parse_layout_events(spec_json, snap_rule, main_road)
    clusters = build_clusters(layout_events)
    lane_overrides = compute_lane_overrides(
        main_road, clusters, junction_template_by_id, snap_rule
    )
    breakpoints, _ = collect_breakpoints_and_reasons(
        main_road, clusters, lane_overrides, snap_rule
    )
    return (
        defaults,
        main_road,
        clusters,
        breakpoints,
        junction_template_by_id,
        lane_overrides,
        snap_rule,
    )


def test_endpoint_catalog_is_deterministic_and_matches_expected():
    (
        defaults,
        main_road,
        clusters,
        breakpoints,
        junction_template_by_id,
        lane_overrides,
        snap_rule,
    ) = _prepare_inputs()

    catalog_first = build_endpoint_catalog(
        defaults=defaults,
        main_road=main_road,
        clusters=clusters,
        breakpoints=breakpoints,
        junction_template_by_id=junction_template_by_id,
        lane_overrides=lane_overrides,
        snap_rule=snap_rule,
    )
    catalog_second = build_endpoint_catalog(
        defaults=defaults,
        main_road=main_road,
        clusters=clusters,
        breakpoints=breakpoints,
        junction_template_by_id=junction_template_by_id,
        lane_overrides=lane_overrides,
        snap_rule=snap_rule,
    )

    assert catalog_first.vehicle_endpoints == catalog_second.vehicle_endpoints
    assert catalog_first.pedestrian_endpoints == catalog_second.pedestrian_endpoints

    expected_vehicle_endpoints = [
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.350.in",
            pos=350,
            category="main_EB",
            edge_id="Edge.Main.EB.250-350",
            lane_count=4,
            is_inbound=True,
            tl_id=None,
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.350.out",
            pos=350,
            category="main_EB",
            edge_id="Edge.Main.EB.350-450",
            lane_count=3,
            is_inbound=False,
            tl_id=None,
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.350.in",
            pos=350,
            category="main_WB",
            edge_id="Edge.Main.WB.450-350",
            lane_count=4,
            is_inbound=True,
            tl_id=None,
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.350.out",
            pos=350,
            category="main_WB",
            edge_id="Edge.Main.WB.350-250",
            lane_count=3,
            is_inbound=False,
            tl_id=None,
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_N.350.in",
            pos=350,
            category="minor_N",
            edge_id="Edge.MinorN.SB.350",
            lane_count=2,
            is_inbound=True,
            tl_id=None,
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_N.350.out",
            pos=350,
            category="minor_N",
            edge_id="Edge.MinorN.NB.350",
            lane_count=1,
            is_inbound=False,
            tl_id=None,
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.650.in",
            pos=650,
            category="main_EB",
            edge_id="Edge.Main.EB.500-650",
            lane_count=5,
            is_inbound=True,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.650.out",
            pos=650,
            category="main_EB",
            edge_id="Edge.Main.EB.650-780",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.650.in",
            pos=650,
            category="main_WB",
            edge_id="Edge.Main.WB.780-650",
            lane_count=5,
            is_inbound=True,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.650.out",
            pos=650,
            category="main_WB",
            edge_id="Edge.Main.WB.650-500",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_N.650.in",
            pos=650,
            category="minor_N",
            edge_id="Edge.MinorN.SB.650",
            lane_count=3,
            is_inbound=True,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_N.650.out",
            pos=650,
            category="minor_N",
            edge_id="Edge.MinorN.NB.650",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_S.650.in",
            pos=650,
            category="minor_S",
            edge_id="Edge.MinorS.NB.650",
            lane_count=3,
            is_inbound=True,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_S.650.out",
            pos=650,
            category="minor_S",
            edge_id="Edge.MinorS.SB.650",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.650.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.900.in",
            pos=900,
            category="main_EB",
            edge_id="Edge.Main.EB.800-900",
            lane_count=4,
            is_inbound=True,
            tl_id="Cluster.900.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.900.out",
            pos=900,
            category="main_EB",
            edge_id="Edge.Main.EB.900-920",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.900.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.900.in",
            pos=900,
            category="main_WB",
            edge_id="Edge.Main.WB.920-900",
            lane_count=4,
            is_inbound=True,
            tl_id="Cluster.900.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.900.out",
            pos=900,
            category="main_WB",
            edge_id="Edge.Main.WB.900-800",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.900.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_S.900.in",
            pos=900,
            category="minor_S",
            edge_id="Edge.MinorS.NB.900",
            lane_count=3,
            is_inbound=True,
            tl_id="Cluster.900.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_S.900.out",
            pos=900,
            category="minor_S",
            edge_id="Edge.MinorS.SB.900",
            lane_count=2,
            is_inbound=False,
            tl_id="Cluster.900.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.1000.in",
            pos=1000,
            category="main_EB",
            edge_id="Edge.Main.EB.920-1000",
            lane_count=4,
            is_inbound=True,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_EB.1000.out",
            pos=1000,
            category="main_EB",
            edge_id="Edge.Main.EB.1000-1020",
            lane_count=3,
            is_inbound=False,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.1000.in",
            pos=1000,
            category="main_WB",
            edge_id="Edge.Main.WB.1020-1000",
            lane_count=4,
            is_inbound=True,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.main_WB.1000.out",
            pos=1000,
            category="main_WB",
            edge_id="Edge.Main.WB.1000-920",
            lane_count=4,
            is_inbound=False,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_N.1000.in",
            pos=1000,
            category="minor_N",
            edge_id="Edge.MinorN.SB.1000",
            lane_count=2,
            is_inbound=True,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_N.1000.out",
            pos=1000,
            category="minor_N",
            edge_id="Edge.MinorN.NB.1000",
            lane_count=2,
            is_inbound=False,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_S.1000.in",
            pos=1000,
            category="minor_S",
            edge_id="Edge.MinorS.NB.1000",
            lane_count=2,
            is_inbound=True,
            tl_id="Cluster.1000.Main",
        ),
        VehicleEndpoint(
            id="Endpoint.Vehicle.minor_S.1000.out",
            pos=1000,
            category="minor_S",
            edge_id="Edge.MinorS.SB.1000",
            lane_count=2,
            is_inbound=False,
            tl_id="Cluster.1000.Main",
        ),
    ]
    expected_pedestrian_endpoints = [
        PedestrianEndpoint(
            id="CrossMid.200.N",
            pos=200,
            movement="ped_mid_EB",
            node_id="Cluster.200.Main",
            edges=("Edge.Main.EB.0-200",),
            width=3.5,
            tl_id="Cluster.200.Main",
        ),
        PedestrianEndpoint(
            id="CrossMid.200.S",
            pos=200,
            movement="ped_mid_WB",
            node_id="Cluster.200.Main",
            edges=("Edge.Main.WB.200-0",),
            width=3.5,
            tl_id="Cluster.200.Main",
        ),
        PedestrianEndpoint(
            id="Cross.350.N",
            pos=350,
            movement="ped_minor_north",
            node_id="Cluster.350.Main",
            edges=("Edge.MinorN.SB.350", "Edge.MinorN.NB.350"),
            width=3.5,
            tl_id=None,
        ),
        PedestrianEndpoint(
            id="Cross.350.W",
            pos=350,
            movement="ped_main_west",
            node_id="Cluster.350.Main",
            edges=("Edge.Main.EB.250-350", "Edge.Main.WB.350-250"),
            width=3.5,
            tl_id=None,
        ),
        PedestrianEndpoint(
            id="Cross.650.N",
            pos=650,
            movement="ped_minor_north",
            node_id="Cluster.650.Main",
            edges=("Edge.MinorN.SB.650", "Edge.MinorN.NB.650"),
            width=3.5,
            tl_id="Cluster.650.Main",
        ),
        PedestrianEndpoint(
            id="Cross.650.S",
            pos=650,
            movement="ped_minor_south",
            node_id="Cluster.650.Main",
            edges=("Edge.MinorS.NB.650", "Edge.MinorS.SB.650"),
            width=3.5,
            tl_id="Cluster.650.Main",
        ),
        PedestrianEndpoint(
            id="Cross.650.W.N",
            pos=650,
            movement="ped_main_west_EB",
            node_id="Cluster.650.Main",
            edges=("Edge.Main.EB.500-650",),
            width=3.5,
            tl_id="Cluster.650.Main",
        ),
        PedestrianEndpoint(
            id="Cross.650.W.S",
            pos=650,
            movement="ped_main_west_WB",
            node_id="Cluster.650.Main",
            edges=("Edge.Main.WB.650-500",),
            width=3.5,
            tl_id="Cluster.650.Main",
        ),
        PedestrianEndpoint(
            id="Cross.650.E.N",
            pos=650,
            movement="ped_main_east_EB",
            node_id="Cluster.650.Main",
            edges=("Edge.Main.EB.650-780",),
            width=3.5,
            tl_id="Cluster.650.Main",
        ),
        PedestrianEndpoint(
            id="Cross.650.E.S",
            pos=650,
            movement="ped_main_east_WB",
            node_id="Cluster.650.Main",
            edges=("Edge.Main.WB.780-650",),
            width=3.5,
            tl_id="Cluster.650.Main",
        ),
        PedestrianEndpoint(
            id="Cross.900.S",
            pos=900,
            movement="ped_minor_south",
            node_id="Cluster.900.Main",
            edges=("Edge.MinorS.NB.900", "Edge.MinorS.SB.900"),
            width=3.5,
            tl_id="Cluster.900.Main",
        ),
        PedestrianEndpoint(
            id="Cross.900.E.N",
            pos=900,
            movement="ped_main_east_EB",
            node_id="Cluster.900.Main",
            edges=("Edge.Main.EB.900-920",),
            width=3.5,
            tl_id="Cluster.900.Main",
        ),
        PedestrianEndpoint(
            id="Cross.900.E.S",
            pos=900,
            movement="ped_main_east_WB",
            node_id="Cluster.900.Main",
            edges=("Edge.Main.WB.920-900",),
            width=3.5,
            tl_id="Cluster.900.Main",
        ),
        PedestrianEndpoint(
            id="Cross.1000.N",
            pos=1000,
            movement="ped_minor_north",
            node_id="Cluster.1000.Main",
            edges=("Edge.MinorN.SB.1000", "Edge.MinorN.NB.1000"),
            width=3.5,
            tl_id="Cluster.1000.Main",
        ),
        PedestrianEndpoint(
            id="Cross.1000.S",
            pos=1000,
            movement="ped_minor_south",
            node_id="Cluster.1000.Main",
            edges=("Edge.MinorS.NB.1000", "Edge.MinorS.SB.1000"),
            width=3.5,
            tl_id="Cluster.1000.Main",
        ),
        PedestrianEndpoint(
            id="Cross.1000.E",
            pos=1000,
            movement="ped_main_east",
            node_id="Cluster.1000.Main",
            edges=("Edge.Main.EB.1000-1020", "Edge.Main.WB.1020-1000"),
            width=3.5,
            tl_id="Cluster.1000.Main",
        ),
        PedestrianEndpoint(
            id="CrossMid.1050",
            pos=1050,
            movement="ped_mid",
            node_id="Cluster.1050.Main",
            edges=("Edge.Main.EB.1020-1050", "Edge.Main.WB.1050-1020"),
            width=3.5,
            tl_id=None,
        ),
    ]
    assert catalog_first.vehicle_endpoints == expected_vehicle_endpoints
    assert catalog_first.pedestrian_endpoints == expected_pedestrian_endpoints
